version: "3.7"

services:
  server:
    # Run webserver nginx on port 80
    # Feel free to modify depending what port is already occupied
    ports:
      - "80:80"
      # - "443:443"
  db:
    # Feel free to modify depending what port is already occupied
    ports:
      - "3305:3306"
